### ISSUE TITLE
can this work in facebook or google family

### ISSUE THREAD

**Issue by Seumi** [ShapManasick/RootSSL-Killer#2]
Thanks for your great work.
This script seem can work on most application using common ssl check，i wonder if this can also work on facebook family(whatsapp,ins)or google family(google play, google map) or other application using custom ssl check

**Comment by ShapManasick** [comment]
> Thanks for your great work.
> This script seem can work on most application using common ssl check，i wonder if this can also work on facebook family(whatsapp,ins)or google family(google play, google map) or other application using custom ssl check
